### ISSUE TITLE
Error when using imported mode with py5bot

### ISSUE THREAD

**Issue by Lioncat2002** [hx2A/py5book#2] opened 2022-04-03 10:33 UTC
I don't know if this is the right place but,
I have been using the py5bot for the jupyter notebook
but when I try to use the `imported mode`
jupyter throws the following error:
```
py5 encountered an error in your code:File "/tmp/ipykernel_5944/933771270.py", line 13, in _py5bot_settings
    8    def _py5bot_settings():
    9        with open('/tmp/tmp3twzer8b/_PY5_STATIC_SETTINGS_CODE_.py', 'r') as f:
    10           exec(
    11               compile(
    12                   _PY5BOT_parsing.transform_py5_code(
--> 13                       _PY5BOT_ast.parse(f.read(), filename='/tmp/tmp3twzer8b/_PY5_STATIC_SETTINGS_CODE_.py', mode='exec'),
    14                   ),
    ..................................................
     _PY5BOT_ast.parse = <function 'parse' ast.py:33>
    ..................................................

File "/usr/lib/python3.9/ast.py", line 50, in parse
    33   def parse(source, filename='<unknown>', mode='exec', *,
    34             type_comments=False, feature_version=None):
 (...)
    46           feature_version = minor
    47       elif feature_version is None:
    48           feature_version = -1
    49       # Else it should be an int giving the minor version for 3.x.
--> 50       return compile(source, filename, mode, flags,
    51                      _feature_version=feature_version)
    ..................................................
     source = '\n    size(300, 200)\n'
     filename = '/tmp/tmp3twzer8b/_PY5_STATIC_SETTINGS_CODE_.py'
     mode = 'exec'
     flags = 1024
    ..................................................

IndentationError: unexpected indent (_PY5_STATIC_SETTINGS_CODE_.py, line 2)
java.lang.IllegalStateException: Component must have a valid peer
	at java.desktop/java.awt.Component$FlipBufferStrategy.getBackBuffer(Component.java:4154)
	at java.desktop/java.awt.Component$FlipBufferStrategy.updateInternalBuffers(Component.java:4137)
	at java.desktop/java.awt.Component$FlipBufferStrategy.revalidate(Component.java:4258)
	at java.desktop/java.awt.Component$FlipBufferStrategy.getDrawGraphics(Component.java:4235)
	at processing.awt.PSurfaceAWT.render(PSurfaceAWT.java:242)
	at processing.awt.PSurfaceAWT$9.callDraw(PSurfaceAWT.java:1441)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:356)
```
it appears that there is an extra indentation in one of the files belonging to py5bot?
Thanks for your help! :)

**Comment by hx2A** [comment] 2022-04-03 11:14
Welcome, @Lioncat2002 !

Can you tell me more about how you are running this? Are you running it locally on your machine? What kind of machine do you have?

Can you provide the py5bot notebook cell that is generating this error?

I am doing a new release very soon and can get a code change in if needed.

**Comment by hx2A** [comment] 2022-04-03 11:47
I'd like to know the sequence of steps to reproduce this. That `/tmp/tmp3twzer8b/_PY5_STATIC_SETTINGS_CODE_.py` nonsense is part of the inner workings of py5bot and shouldn't be revealed to users when there is an error, even if the user made a mistake in how they are using py5.

When I put this in a py5bot notebook cell:

```ipython
    size(300, 200)

rect(10, 20, 30, 40)
```

I get this response:

```text
There is an indentation problem with your code on line 1:
--> 1        size(300, 200)
             ^
```

That's a helpful error for users and what you should see if there is an indentation problem.

The code `size(300, 200)` is code you must have wrote, but py5bot will not add the indentation to that. It must be coming from somewhere else.

Also, so we are using the same terminology, py5bot uses "static mode" because what you create with it does not animate. "imported mode" can animate sketches, and is run from the py5 kernel. Are you by any chance telling Jupyter to switch the notebook kernel from one to the other? Even then, such a switch shouldn't create the error you received.

**Comment by hx2A** [comment] 2022-04-03 19:12
I figured out *a* way to reproduce this, which might not be exactly what you did, but given what you wrote, I think it is close.

When I have a notebook using py5bot kernel and I put this in a cell

```ipython
def setup():
    size(300, 200)
    rect(10, 20, 30, 40)
```

I get the same error that you get. But I shouldn't be defining a `setup()` function in py5bot like that. Instead, all code should be written in "static mode":

```ipython
size(300, 200)
rect(10, 20, 30, 40)
```

Please refer to the documentation to read more about the [different py5 modes](http://py5.ixora.io/content/py5_modes.html).

If you create a notebook that uses the py5bot kernel, all code should be in "static mode." If you want to write something in "imported mode", the best choice is to create a new notebook that uses the py5 kernel. You can also tell Jupyter to switch the notebook's kernel from one to the other, but that can lead to confusion.

py5bot needs to be improved here to give a better error message. The error message you got is ugly and off-putting to new users.

**Comment by Lioncat2002** [comment] 2022-04-04 06:17
Sorry for the late reply 
but yeah I had been trying to use the "imported mode" 
now I understand where it went wrong,
Thank you so much!

**Comment by hx2A** [comment] 2022-04-04 19:11
You are welcome! I am glad we could figure this out.

I am going to close this issue but I created a [new issue in the py5generator repo](https://github.com/hx2A/py5generator/issues/74) to track what I'd like to do to improve py5 & py5bot for this.

Thank you again for your interest in py5 and for your contribution here, which helped me understand how to make py5 more user friendly.

**Closed as completed by hx2A** 2022-04-04 19:11 UTC
